Develop
Dmitrii-Zz/java-filmorate pull request #36
Opened 2023-10-16 12:45 UTC by Dmitrii-Zz

2023-10-17 12:34 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь несколько замечаний. Также добавьте, пожалуйста, в README файл описание проекта, и список фич, который был реализован

2023-10-17 12:34 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre() {
Можно использовать `@NoArgsConstructor`

2023-10-17 12:34 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/FilmDbStorage.java
> +            throw new RuntimeException(e);
Лучше бросать не общее, а свое кастомное непроверяемое исключение, так потом понятнее код, а также проще потом разобрать ошибки

2023-10-17 12:34 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    private String eventType;
Лучше было бы ввести enum - так была бы меньше верояность ошибки

2023-10-18 14:28 UTC, SergeyPrisyazhnyuk approved these changes
К коду претензий нет, тесты проходит.

2023-10-19 11:50 UTC, mikita95 approved these changes
Все отлично. Можно мержить пу-реквест

2023-10-20 14:58 UTC, merged