Controllers films users
Dmitrii-Zz/java-filmorate pull request #5
Opened 2023-08-15 07:36 UTC by Dmitrii-Zz

2023-08-15 18:25 UTC, mikita95 commented on mvnw.cmd
Этот файл не нужен, можно удалить

2023-08-15 18:28 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Exception {
Это исключение лучше сделать непроверяемым, так проще писать и читать код

2023-08-15 18:29 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<Integer, User> users = new HashMap<>();
Лучше было разделить код на два слоя: контроллеры и хранилища, так как у них разная ответственность, а сейчас это все смешано. Так было бы легче покрыть код тестами, поддерживать его и расширять

2023-08-15 18:30 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private boolean isValidate;
Эта переменная используется только в методах, там ее и нужно объявить. Здесь не Паскаль :)

2023-08-15 18:33 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (login != null) {
Этот код сейчас отформатирован неверно. Все вложенные секции, даже однострочные, должны быть обернуты в фигурные скобки. Так же стоит использовать "охранное" выражение, то есть так:
```
if (login == null) {
    return false;
}
if (login.isBlank()) {
    return false;
}
...
```
так код легче читать.

2023-08-15 18:34 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            char[] massiveCharLogin = login.toCharArray();
Можно просто `login.contains(' ');` (https://www.baeldung.com/string/contains)

2023-08-15 18:35 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (name.isBlank()) user.setName(user.getLogin());
Все вложенные секции, даже однострочные, нужно обернуть в фигурные скобки

2023-08-15 18:35 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null) return false;
Все вложенные секции, даже однострочные, нужно обернуть в фигурные скобки

2023-08-15 18:36 UTC, mikita95 commented on pom.xml
> +		<dependency>
Эта зависимость уже должна быть в spring-boot-starter-test

2023-08-15 18:37 UTC, mikita95 commented on pom.xml
> +			<groupId>com.google.code.gson</groupId>
Кажется, сейчас нигде не используется gson, можно удалить эту зависимость

2023-08-16 04:55 UTC, Dmitrii-Zz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Exception {
Не совсем понимаю "проще писать и читать код". Кроме того, что собственное исключение будет наследоваться от RuntimeException, а не от Exception ничего не поменяется в коде, в чем преимущество первого от второго при чтении кода?

2023-08-16 05:03 UTC, Dmitrii-Zz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<Integer, User> users = new HashMap<>();
Правильно ли понимаю, что нужно создать пакет ru.yandex.prcticum.filmorate.service, в котором необходимо написать классы UserService и FilmService, в которых будут поля id и мапы для хранения данных. А весь код валидации данных  пользователя и фильма можно оставить в пакете controller.

2023-08-16 15:57 UTC, Dmitrii-Zz commented on pom.xml
> +		</dependency>
Если убрать эту зависимость, то не работают аннотации @Valid в сигнатуре метода и аннотации @NotNull и т.д. над полями объектов-моделей

2023-08-17 11:53 UTC, mikita95 requested changes
Все почти отлично :) Нужно только немного поправить работу с спрингом. Если что-то не понятно по спрингу, то можно вернуться к курсу или обратиться к наставнику.

2023-08-17 11:53 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmRepository filmRepository = new FilmRepository();
Не нужно создавать теперь класс вручную через конструктор :)
Нужно пользоваться auto-injection из спринга.

То есть в данном случае можно сделать так:
```
public class FilmController {
    private final FilmRepository filmRepository;
    ...
    @Autowired
    public FilmController(FilmRepository filmRepository) {
        this.filmRepository = filmRepository;
    } 
    ...
```

Также можно не указывать Autowired, если используется конструктор. Также можно воспользоваться аннотацией lombok `@RequiredArgsConstructor`, чтобы не писать конструктор вручную.

Так спринг сам сконструирует объект репозиторий и сделать его singleton - то есть будет только один объект в контексте спринга.

2023-08-17 11:53 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserRepository userRepository = new UserRepository();
Нужно пользоваться injection из спринга

2023-08-18 14:39 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-08-18 15:21 UTC, merged