Add database
Dmitrii-Zz/java-filmorate pull request #7
Opened 2023-09-23 16:37 UTC by Dmitrii-Zz

2023-09-24 15:00 UTC, mikita95 requested changes
Все сделано хорошо. Оставил лишь нескольк небольших замечаний.

2023-09-26 11:31 UTC, Dmitrii-Zz commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/FilmDbStorage.java
> +        String sqlRequest =
В классе FilmDbStorage указали замечание, что перед выполнением метода public Film update(Film film) лучше проверить существование фильма. В проекте перед вызовом этого метода в классе filmService в методе public Film updateFilm(Film film) вызывается метод validateIdFilm(film.getId()), который проверяет наличие фильма в БД. Это и есть проверка на существование фильма. Получается дополнительно ничего не нужно делать или я неверно понял замечание)

2023-09-27 23:42 UTC, mikita95 approved these changes
Все отлично. Можно мержить пул-реквест

2023-09-27 23:42 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/FilmDbStorage.java
> +                String.format("INSERT INTO films (name, description, release_date, duration, rating_id) " +
Лучше использовать операцию merge, иначе может возникнуть исключение при добавление одногг и того же фильма

2023-10-09 11:28 UTC, merged